=== yborisovstc/fapws/etc/objspec.dtd
<!-- TODO [YB] No error whyle spec parsing when data type entity missed -->
<!-- TODO [DONE] [YB] external entities shall not be used as attr value - against XML WFC -->


<!-- State data types -->
<!--
     StInt, StUint8, StUint32, StBool
     -->


<!-- Logging data. States the data of FAP element that should be logged -->
<!ELEMENT logdata EMPTY>

<!-- Logspec includes attribute "levent" and assosiated logging data set -->
<!ELEMENT logspec (logdata+)>

<!-- 
     Mutation - addition
-->
<!ELEMENT add (inp*, out*, logspec*, trans*, iobject* , state*, conn*, ext*, extc*)>

<!-- 
     Mutation - change content
-->
<!ELEMENT changecont EMPTY>

<!-- 
     Mutation - moving
-->
<!ELEMENT move EMPTY>


<!-- 
     Node
-->
<!ELEMENT node EMPTY>

<!ELEMENT state (logspec*, inp*, trans*)>

<!ELEMENT trans ANY>

<!-- 
     Object inherited
     This is the base spec of the object
     The spec contains pointing to parent (attr type) and spec for parents mutation
     Mutation can be adding, deleting, changing, and special mutation
-->
<!ELEMENT iobject (inp*, out*, logspec*, trans*, iobject* , state*, conn*, ext*, extc*, add*, rm*, chg*, changecont*, move*)>
 
<!-- Removing node -->
<!ELEMENT rm EMPTY >

<!-- Changing node attribute-->
<!ELEMENT chg EMPTY >

<!-- Output -->
<!ELEMENT out (src*, dest*)>

<!-- Input - connection point that consumes variable data 
     src - sources provided by connection point 
     dest - destinations requested by coneection point
     -->
<!ELEMENT inp (src*, dest*)>

<!-- Transition function -->
<!ELEMENT transf (dep*)>

<!-- Connection -->
<!ELEMENT conn EMPTY >

<!-- Connecting Extention -->
<!ELEMENT ext EMPTY >

<!-- Custom Connecting Extention -->
<!ELEMENT extc (srcext*, dstext*)>

<!-- Connection point source pin -->
<!ELEMENT src EMPTY >

<!-- Connection point dest -->
<!ELEMENT dest EMPTY >

<!-- Custom extention source pin binding  -->
<!ELEMENT srcext EMPTY >

<!-- Custom extention destination pin binding  -->
<!ELEMENT dstext EMPTY >

<!-- Dependency in state connection -->
<!ELEMENT dep EMPTY >

<!-- Logging event: tran - transitioning, upd - updated, cre - created, any - all events -->
<!ATTLIST logspec event (tran | upd | cre | any) #REQUIRED>

<!-- Logging data: tran - transition expressions, cur - current value, new - new value, dep - pependencies -->
<!ATTLIST logdata id (trex | cur | new | dep) #REQUIRED>

<!-- Inherited Object  attributes:
     type - parent name,
     id - instance name,
     -->
<!ATTLIST iobject 
   type CDATA #REQUIRED
   id CDATA #REQUIRED
   quiet (yes) #IMPLIED
>

<!-- State added attributes:
  mut - mutation, on missing assumen "Add"
  type - type of state
  id - identification of instance
  transf - transtion function 
  init - initial value
  -->
<!ATTLIST state 
    mut (Add | Del | Change) #IMPLIED
    type CDATA #IMPLIED
    id CDATA #REQUIRED
    len CDATA #IMPLIED
    transf CDATA #IMPLIED
    init CDATA #IMPLIED
>

<!--  Input attributes -->
<!ATTLIST inp 
    id CDATA #REQUIRED
>

<!--  Output attributes -->
<!ATTLIST out 
    id CDATA #REQUIRED
>

<!--  Connection point source 
      type is "State" by default
      -->
<!ATTLIST src 
    id CDATA #REQUIRED
    type CDATA #IMPLIED 
>

<!--  Connection point destination 
      type is "State" by default
      -->
<!ATTLIST dest 
    id CDATA #REQUIRED
    type CDATA #IMPLIED 
>

<!-- Connections
   id - subject of connection, input of state or subsystem
   pair - object of connection
     -->
<!ATTLIST conn 
    id  CDATA #REQUIRED
    pair  CDATA #REQUIRED
>

<!-- Connecting extention
   id - subject - extention
   pair - object
     -->
<!ATTLIST ext 
    id  CDATA #REQUIRED
    pair  CDATA #REQUIRED
>

<!-- Custom Connecting extention
   id - subject 
     -->
<!ATTLIST extc 
    id  CDATA #REQUIRED
>

<!-- Custom Connecting extention - source extention
   id - pin id 
   pair - connecitn pair
     -->
<!ATTLIST srcext 
    id  CDATA #REQUIRED
    pair  CDATA #REQUIRED
>

<!-- Custom Connecting extention - destination extention
   id - pin id 
   pair - connecitn pair
     -->
<!ATTLIST dstext 
    id  CDATA #REQUIRED
    pair  CDATA #REQUIRED
>

<!-- Adding node attributes:
  node - mutated node - DES URI
  -->
<!ATTLIST add 
    node CDATA #IMPLIED
>

<!-- Removing node attributes:
  node - mutated node - DES URI
  -->
<!ATTLIST rm 
    node CDATA #IMPLIED
>

<!-- Change  attributes:
     node - mutated node - DES URI
     attr - attr name,
     val - attr value,
     -->
<!ATTLIST chg
   node CDATA #REQUIRED
   attr CDATA #REQUIRED
   val CDATA #REQUIRED
>

<!-- Change content attributes:
     node - changed node
     val - new value,
     -->
<!ATTLIST changecont
   node CDATA #REQUIRED
   val CDATA #REQUIRED
>

<!-- Moving attributes:
     id - moved node name
     node - base node, to top if omitted
     -->
<!ATTLIST move
   id CDATA #REQUIRED
   node CDATA #IMPLIED
>

<!-- Environment attr -->
<!--
<!ATTLIST caeenv 
   root CDATA #REQUIRED
>
-->

=== yborisovstc/fapws/test/ut_emtran_vect.xml
<?xml version="1.0" ?>

<!-- Specification of FAP visualization module for GTK -->
<!--
     -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="main">
    <out id="output"/>
    <logspec  event="cre"> <logdata id="new"/> </logspec>
    <logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
    <state type="StVectF" id="test_coord_pf" init="{1.0,3.0}">
	<logspec  event="cre"> <logdata id="new"/> </logspec>
	<logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	<inp id="self"/>
	<trans> add inp self {1.0,1.0} </trans>
    </state>
    <conn id="state:test_coord_pf/inp:self" pair="state:test_coord_pf/out:output"/>
    <ext id="out:output" pair="state:test_coord_pf/out:output"/>
</iobject> <!-- main -->

=== yborisovstc/fapws/test/ut_modul_incr.xml
<?xml version="1.0" ?>

<!-- Unit test for modularity - parent for incrementors -->
<!--
     -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="root" quiet="yes">
    <logspec  event="cre"> <logdata id="new"/> </logspec>

    <iobject type="none" id="incrementor" quiet="yes">
	<out id="output"/>

	<!-- State that contains data -->
	<state type="StInt" id="S_Count" init="5"> 
	    <logspec event="cre"> <logdata id="new"/> </logspec> 
	    <logspec event="upd"> <logdata id="new"/> </logspec> 
	    <inp id="self"/> 
	    <trans> add inp self 1 </trans>
	</state>

	<conn id="state%S_Count.self" pair="state%S_Count.output"/> 
	<ext id="output" pair="state%S_Count.output"/>

    </iobject> <!-- incrementor -->

</iobject> <!-- Test -->

=== yborisovstc/fapws/test/ut_modul_loc1.xml
<?xml version="1.0" ?>

<!-- Unit test for modularity - access in local context -->
<!--
     -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="root">
    <out id="output"/>
    <logspec  event="cre"> <logdata id="new"/> </logspec>

    <iobject type="none" id="incrementor">
	<out id="output"/>

	<!-- State that contains data -->
	<state type="StInt" id="S_Count" init="5"> 
	    <logspec event="cre"> <logdata id="new"/> </logspec> 
	    <logspec event="upd"> <logdata id="new"/> </logspec> 
	    <inp id="self"/> 
	    <trans> add inp self 1 </trans>
	</state>

	<conn id="state:S_Count/inp:self" pair="state:S_Count/out:output"/> 
	<ext id="out:output" pair="state:S_Count/out:output"/>

    </iobject> <!-- incrementor -->

    <iobject type="none" id="Box">
	<out id="output"/>
	<iobject type="incrementor" id="My_Incr">
	</iobject> <!-- My_Incr -->
	<ext id="out:output" pair="My_Incr/out:output"/>
    </iobject>
    <ext id="out:output" pair="Box/out:output"/>

</iobject> <!-- Test -->

=== yborisovstc/fapws/test/ut_modul_loc.xml
<?xml version="1.0" ?>

<!-- Unit test for modularity - access in local context -->
<!--
     -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="root">
    <out id="output"/>
    <logspec  event="cre"> <logdata id="new"/> </logspec>

    <iobject type="none" id="incrementor">
	<out id="output"/>

	<!-- State that contains data -->
	<state type="StInt" id="S_Count" init="5"> 
	    <logspec event="cre"> <logdata id="new"/> </logspec> 
	    <logspec event="upd"> <logdata id="new"/> </logspec> 
	    <inp id="self"/> 
	    <trans> add inp self 1 </trans>
	</state>

	<conn id="state%S_Count.self" pair="state%S_Count.output"/> 
	<ext id="output" pair="state%S_Count.output"/>

    </iobject> <!-- incrementor -->

    <iobject type="none" id="Box">
	<out id="output"/>
	<iobject type="../incrementor" id="My_Incr">
	</iobject> <!-- My_Incr -->
	<ext id="output" pair="My_Incr.output"/>
    </iobject>
    <ext id="output" pair="Box.output"/>

</iobject> <!-- Test -->

=== yborisovstc/fapws/test/ut_emtran_vectgf.xml
<?xml version="1.0" ?>

<!-- Unit test for embedded generic vector of float -->
<!--
     -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="main">
    <out id="output"/>
    <out id="outp_smult"/>
    <logspec  event="cre"> <logdata id="new"/> </logspec>
    <logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
    <state type="TVectG" id="incr" init="(Float 3) 1.0 3.0 5.0">
	<logspec  event="cre"> <logdata id="new"/> </logspec>
	<logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	<inp id="self"/>
	<trans> add inp self TVectG (Float 3) 1.0 2.0 3.0</trans>
    </state>

    <state type="Float" id="smult" init="0.0">
	<logspec  event="cre"> <logdata id="new"/> </logspec>
	<logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	<inp id="inp1"/>
	<trans> smul inp inp1 TVectG (Float 3) 2.0 1.0 1.0</trans>
    </state>
    <conn id="state:incr/inp:self" pair="state:incr/out:output"/>
    <conn id="state:smult/inp:inp1" pair="state:incr/out:output"/>
    <ext id="out:output" pair="state:incr/out:output"/>
    <ext id="out:outp_smult" pair="state:smult/out:output"/>
</iobject> <!-- main -->

=== yborisovstc/fapws/test/ut_embmod_vect.xml
<?xml version="1.0" ?>

<!-- Specification of FAP environment for unit test for embedded module "Vector" -->
<!--
     -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="main_test">

    <out id="rock">
	<src id="coord"/> <src id="mass"/> 
    </out>

    <logspec event="tran"> <logdata id="trex"/></logspec> 

    <iobject type="file:../modules/vector.xml#vector" id="my_vector" quiet="yes"/> 

    <iobject type="none" id="Rock" quiet="yes"> 
	<out id="coord"/>
	<out id="mass"/>
	<out id="outp"> <src id="coord"/> <src id="mass"/> </out>

	<logspec  event="cre"> <logdata id="new"/> </logspec>

	<trans>
	    let KAccDef :: Vector := 0.0 -8.9
	</trans>

	<state type="Float" id="mass" init="2.0"> 
	    <logspec event="upd"> <logdata id="new"/> </logspec> 
	</state>

	<state type="Vector" id="coord" init="0.0 1.0"> 
	    <logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	    <logspec event="tran"> <logdata id="trex"/></logspec> 
	    <inp id="self"/> <inp id="velocity"/> 
	    <trans> 
		let coord :: Vector := add inp self inp velocity
		let bang :: TBool := le VectY coord 0.0
		if bang KVect0 coord
	    </trans>
	</state>

	<state type="Vector" id="velocity" init="80.0 80.0"> 
	    <logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	    <logspec event="tran"> <logdata id="trex"/></logspec> 
	    <inp id="self"/><inp id="coord"/> 
	    <trans> 
		let bang :: TBool := le VectY inp coord 0.0
		let vel :: Vector := add inp self KAccDef
		if bang KVect0 vel
	    </trans>
	</state>

	<conn id="state:coord/inp:self" pair="state:coord/out:output"/> 
	<conn id="state:coord/inp:velocity" pair="state:velocity/out:output"/> 
	<conn id="state:velocity/inp:coord" pair="state:coord/out:output"/> 
	<conn id="state:velocity/inp:self" pair="state:velocity/out:output"/> 

	<ext id="out:coord" pair="state:coord/out:output"/>
	<ext id="out:mass" pair="state:mass/out:output"/>

    </iobject> <!-- Rock -->

    <iobject type="Rock" id="rock_1" > <chg node="state:mass" attr="init" val="7"/> </iobject>

    <extc id="out:rock"> <srcext id="coord" pair="rock_1/out:coord"/> <srcext id="mass" pair="rock_1/out:mass"/> </extc>

</iobject> <!-- test -->

=== yborisovstc/fapws/test/ut_spec_ext_mut.xml
<?xml version="1.0" ?>

<!-- Specification of FAP environment for unit test for extended inputs and object mutation -->
<!--
     There are several "snails" that are crawling to one direction
     The the less mass of snail the much its velocity  
     The snail that is crawling first eat more food and thus increase its mass
     The snail that falls behind gets less food and thus loosing its mass
     -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="main_test">
    <iobject type="none" id="snail" quiet="yes"> 
	<inp id="coord_others"/>
	<out id="coord"/>

	<logspec  event="cre"> <logdata id="new"/> </logspec>

	<state type="StUint32" id="mass" transf="trans_mass" init="2"> 
	    <logspec event="upd"> <logdata id="new"/> </logspec> 
	    <inp id="coord_self"/> <inp id="coord_others"/> </state>

	<state type="StUint32" id="coord" len="4" transf="trans_coord" init="0"> 
	    <logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	    <inp id="self"/> <inp id="mass"/> 
	</state>

	<conn id="state:mass/inp:coord_self" pair="state:coord/out:output"/> 
	<conn id="state:coord/inp:self" pair="state:coord/out:output"/> 
	<conn id="state:coord/inp:mass" pair="state:mass/out:output"/>

	<ext id="inp:coord_others" pair="state:mass/inp:coord_others"/>
	<ext id="out:coord" pair="state:coord/out:output"/>

    </iobject> <!-- snail -->

    <iobject type="snail" id="snail_1" > <chg node="state:mass" attr="init" val="7"/> </iobject>
    <iobject type="snail" id="snail_2" > <chg node="state:mass" attr="init" val="3"/> </iobject>
    <iobject type="snail" id="snail_3" > <chg node="state:mass" attr="init" val="16"/> </iobject>

    <conn id="snail_1/inp:coord_others" pair="snail_2/out:coord"/><conn id="snail_1/inp:coord_others" pair="snail_3/out:coord"/>
    <conn id="snail_2/inp:coord_others" pair="snail_1/out:coord"/> <conn id="snail_2/inp:coord_others" pair="snail_3/out:coord"/>
    <conn id="snail_3/inp:coord_others" pair="snail_1/out:coord"/> <conn id="snail_3/inp:coord_others" pair="snail_2/out:coord"/>

</iobject> <!-- test -->

=== yborisovstc/fapws/test/ut_conn_spec.xml
<?xml version="1.0" ?>

<!-- Unit test for connections -->
<!--
     There are several "snails" that are crawling to one direction
     The the less mass of snail the much its velocity  
     The snail that is crawling first eat more food and thus increase its mass
     The snail that falls behind gets less food and thus loosing its mass
     Also the snail can be frugal, which doesn't eat the whole portion, thus more food remains for the followers 

     The following use cases are tested:
     1. Object output extending of multiple state outputs to one bus
     2. Object input extending of multiple state inputs to one bus
     3. State input multiple connestion to outputs (snail.mass.neighbor to snail.out) 

     -->

 <!-- State [mass], inputs
 coord_self - corrdinates of snail
 frugal - if the snail is frugal
 neighbor - status of other snails: coordinate and sign of frugality -->

<!DOCTYPE  iobject SYSTEM "/usr/share/fapws/conf/objspec.dtd"> 

<iobject type="none" id="main_test">
    <iobject type="none" id="snail" quiet="yes"> 

	<inp id="neighbor">
	    <dest id="coord"/> <dest id="frugal"/> 
	</inp>
	<out id="coord"/>
	<!-- Custom output connection point: contains two pins on srcs: [coord] and [vip] -->
	<out id="outp">
	    <src id="coord"/> <src id="frugal"/> 
	</out>

	<logspec  event="cre"> <logdata id="new"/> </logspec>

	<state type="StUint32" id="mass" transf="trans_mass" init="2"> 
	    <logspec event="upd"> <logdata id="new"/> </logspec> 
	    <inp id="coord_self"/> <inp id="frugal"/> 
	    <inp id="neighbor"> 
		<dest id="coord"/> <dest id="frugal"/> 
	    </inp>
	</state>

	<state type="StUint32" id="coord" len="4" transf="trans_coord" init="0"> 
	    <logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	    <inp id="self"/> <inp id="mass"/> 
	</state>

	<state type="StBool" id="frugal" len="4" transf="trans_frugal" init="0"> 
	    <logspec event="upd"> <logdata id="cur"/> <logdata id="new"/> </logspec> 
	    <inp id="self"/> <inp id="coord"/> <inp id="coord_other"/> 
	</state>

	<conn id="state:mass/inp:coord_self" pair="state:coord/out:output"/> 
	<conn id="state:mass/inp:frugal" pair="state:frugal/out:output"/> 
	<conn id="state:coord/inp:self" pair="state:coord/out:output"/> 
	<conn id="state:coord/inp:mass" pair="state:mass/out:output"/>
	<conn id="state:frugal/inp:self" pair="state:frugal/out:output"/>
	<conn id="state:frugal/inp:coord" pair="state:coord/out:output"/>

	<ext id="inp:neighbor" pair="state:mass/inp:neighbor"/>
	<ext id="out:coord" pair="state:coord/out:output"/>
	<extc id="out:outp">
	    <srcext id="coord" pair="state:coord/out:output"/>
	    <srcext id="frugal" pair="state:frugal/out:output"/>
	</extc>
	<extc id="inp:neighbor">
	    <dstext id="coord" pair="state:frugal/inp:coord_other"/>
	</extc>

    </iobject> <!-- snail -->

    <iobject type="snail" id="snail_1" > <chg node="state:mass" attr="init" val="7"/> </iobject>
    <iobject type="snail" id="snail_2" > <chg node="state:mass" attr="init" val="3"/> </iobject>
    <iobject type="snail" id="snail_3" > 
	<chg node="state:mass" attr="init" val="16"/> 
	<chg node="state:frugal" attr="init" val="True"/> 
    </iobject>

    <conn id="snail_1/inp:neighbor" pair="snail_2/out:outp"/><conn id="snail_1/inp:neighbor" pair="snail_3/out:outp"/>
    <conn id="snail_2/inp:neighbor" pair="snail_1/out:outp"/> <conn id="snail_2/inp:neighbor" pair="snail_3/out:outp"/>
    <conn id="snail_3/inp:neighbor" pair="snail_1/out:outp"/> <conn id="snail_3/inp:neighbor" pair="snail_2/out:outp"/>

</iobject> <!-- test -->
